In [4]:
#from pandas import Series,DataFrame
import pandas as pd


In [8]:
ob=pd.Series([1,2,3,4])

In [9]:
ob

0    1
1    2
2    3
3    4
dtype: int64

In [10]:
ob.values

array([1, 2, 3, 4], dtype=int64)

In [11]:
ob.index

RangeIndex(start=0, stop=4, step=1)

In [13]:
ob2=pd.Series([1,2,3,4],index=['a','b','c','d'])

In [14]:
ob2

a    1
b    2
c    3
d    4
dtype: int64

In [15]:
ob2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [16]:
ob2.values

array([1, 2, 3, 4], dtype=int64)

In [17]:
ob2[ob2>2]

c    3
d    4
dtype: int64

In [18]:
ob2*5  #index remains unaffected , only values are affected

a     5
b    10
c    15
d    20
dtype: int64

In [24]:
import numpy as np
np.exp(ob2)  #e^x

a     2.718282
b     7.389056
c    20.085537
d    54.598150
dtype: float64

In [21]:
'd' in ob2  # inorder to access presence of any index

True

In [12]:
#entire dicitionary can also be converted into index and series

In [25]:
sdata={'khi':4,'lhr':7, 'isl':0}

In [26]:
ob3=pd.Series(sdata)

In [27]:
ob3

khi    4
lhr    7
isl    0
dtype: int64

In [29]:
data={'khi':20,'Isl':30,'lhr':10}
States=['khi','mlt','lhr']
ob4=pd.Series(data,index=States)

In [30]:
ob4

khi    20.0
mlt     NaN
lhr    10.0
dtype: float64

In [31]:
pd.isnull(ob4) #alternative ob4.isnull()

khi    False
mlt     True
lhr    False
dtype: bool

In [32]:
pd.notnull(ob4)

khi     True
mlt    False
lhr     True
dtype: bool

In [33]:
ob

0    1
1    2
2    3
3    4
dtype: int64

In [36]:
ob3

khi    4
lhr    7
isl    0
dtype: int64

In [37]:
ob4

khi    20.0
mlt     NaN
lhr    10.0
dtype: float64

In [38]:
ob3+ob4

isl     NaN
khi    24.0
lhr    17.0
mlt     NaN
dtype: float64

In [39]:
ob4.name="cities"

In [43]:
ob4.index.name="states"

In [45]:
ob4

states
khi    20.0
mlt     NaN
lhr    10.0
Name: cities, dtype: float64

In [46]:
#A Series’s index can be altered in place by assignment
ob4.index=['bob','steve','jeff']
ob4

bob      20.0
steve     NaN
jeff     10.0
Name: cities, dtype: float64

In [50]:
import pandas as pd

data = {'year': [2000, 2001, 2002, 2001, 2002], 
        'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],  
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]} 
frame = pd.DataFrame(data,index=['a','b','c','d','e'])
frame

year   state  pop
a  2000    Ohio  1.5
b  2001    Ohio  1.7
c  2002    Ohio  3.6
d  2001  Nevada  2.4
e  2002  Nevada  2.9

In [51]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])


year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [53]:
pd.DataFrame(data, columns=['year', 'pop'],index=['a','b','c','d','e'])

year  pop
a  2000  1.5
b  2001  1.7
c  2002  3.6
d  2001  2.4
e  2002  2.9

In [55]:
frame2=pd.DataFrame(data, columns=['year', 'pop','state','dept'],index=['one','two','three','four','five'])
frame2

year  pop   state dept
one    2000  1.5    Ohio  NaN
two    2001  1.7    Ohio  NaN
three  2002  3.6    Ohio  NaN
four   2001  2.4  Nevada  NaN
five   2002  2.9  Nevada  NaN

In [56]:
frame2.columns 

Index(['year', 'pop', 'state', 'dept'], dtype='object')

In [57]:
#A column in a DataFrame can be retrieved as a Series either by dict-like notation or by attribute:
frame2['state']
#or
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [58]:
frame2.year


one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [59]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [62]:
frame2.ix['three']

C:\Users\kumail\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


year     2002
pop       3.6
state    Ohio
dept      NaN
Name: three, dtype: object

In [64]:
frame2['debt']=16.5
frame2

year  pop   state dept  debt
one    2000  1.5    Ohio  NaN  16.5
two    2001  1.7    Ohio  NaN  16.5
three  2002  3.6    Ohio  NaN  16.5
four   2001  2.4  Nevada  NaN  16.5
five   2002  2.9  Nevada  NaN  16.5

In [65]:
frame2['dept']=0
frame2

year  pop   state  dept  debt
one    2000  1.5    Ohio     0  16.5
two    2001  1.7    Ohio     0  16.5
three  2002  3.6    Ohio     0  16.5
four   2001  2.4  Nevada     0  16.5
five   2002  2.9  Nevada     0  16.5

In [81]:
import numpy as np
frame2['dept']=np.arange(5.)
frame2

year  pop   state  dept  debt
one    2000  1.5    Ohio   0.0  16.5
two    2001  1.7    Ohio   1.0  16.5
three  2002  3.6    Ohio   2.0  16.5
four   2001  2.4  Nevada   3.0  16.5
five   2002  2.9  Nevada   4.0  16.5

In [82]:
frame2.loc['three']

year     2002
pop       3.6
state    Ohio
dept        2
debt     16.5
Name: three, dtype: object

In [83]:
val=pd.Series([-1.2,-1.5,-1.7], index=['two','three','five'])
frame2['dept']=val
frame2

year  pop   state  dept  debt
one    2000  1.5    Ohio   NaN  16.5
two    2001  1.7    Ohio  -1.2  16.5
three  2002  3.6    Ohio  -1.5  16.5
four   2001  2.4  Nevada   NaN  16.5
five   2002  2.9  Nevada  -1.7  16.5

In [91]:
frame2['eastern']=frame2.state=='Ohio'
frame2

year  pop   state  dept  debt  eastern
one    2000  1.5    Ohio   NaN  16.5     True
two    2001  1.7    Ohio  -1.2  16.5     True
three  2002  3.6    Ohio  -1.5  16.5     True
four   2001  2.4  Nevada   NaN  16.5    False
five   2002  2.9  Nevada  -1.7  16.5    False

In [92]:
del frame2['eastern']

In [93]:
frame2.columns

Index(['year', 'pop', 'state', 'dept', 'debt'], dtype='object')

In [94]:
frame2

year  pop   state  dept  debt
one    2000  1.5    Ohio   NaN  16.5
two    2001  1.7    Ohio  -1.2  16.5
three  2002  3.6    Ohio  -1.5  16.5
four   2001  2.4  Nevada   NaN  16.5
five   2002  2.9  Nevada  -1.7  16.5

In [96]:
#another way 
pop={'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5 ,2001:1.7,2002:3.6}}
frame3=pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [97]:
frame3.T #transpose

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [98]:
frame3.columns.name="state"
frame3.index.name='year'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [99]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

# Index Object

In [100]:
obj=pd.Series(range(3),index=['a','b','c'])
obj

a    0
b    1
c    2
dtype: int64

In [102]:
index=obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [104]:
index[:2]

Index(['a', 'b'], dtype='object')

In [105]:
index[1:]

Index(['b', 'c'], dtype='object')

In [108]:
#we cant change index directly
index[1]='d'

TypeError: Index does not support mutable operations

In [110]:
labels=pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [111]:
obj2=pd.Series([1.5,-2.5,0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [115]:
ob2.index is labels

False

In [116]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [133]:
dup_labels=pd.Index(['mon','tues','wed','thurs','fri','sat','sun'])
dup_labels

Index(['mon', 'tues', 'wed', 'thurs', 'fri', 'sat', 'sun'], dtype='object')

In [134]:
dup_labels2=pd.Index(['fri','sat','sun','wed'])
dup_labels2

Index(['fri', 'sat', 'sun', 'wed'], dtype='object')

In [135]:
#now you can also append the index dup_labels2 on dup_labels and form new label d (in this case)
d=dup_labels.append(dup_labels2)
d

Index(['mon', 'tues', 'wed', 'thurs', 'fri', 'sat', 'sun', 'fri', 'sat', 'sun',
       'wed'],
      dtype='object')

In [139]:
difference=dup_labels.difference(dup_labels2)
difference

Index(['mon', 'thurs', 'tues'], dtype='object')

In [140]:
intersection=dup_labels.intersection(dup_labels2)
intersection

Index(['wed', 'fri', 'sat', 'sun'], dtype='object')

In [141]:
union=difference.union(intersection)
union

Index(['fri', 'mon', 'sat', 'sun', 'thurs', 'tues', 'wed'], dtype='object')

In [145]:
a=pd.Series([1,2,3,4])
b=pd.Series([1,3,5,6])
K=a.isin(b)
K

0     True
1    False
2     True
3    False
dtype: bool

In [ ]:
# Some Index methods and properties 
#delete Compute new Index with element at index i deleted 
#drop Compute new Index by deleting passed values 
#insert Compute new Index by inserting element at index i 
#is_monotonic Returns True if each element is greater than or equal to the previous element
#is_unique Returns True if the Index has no duplicate values unique Compute the array of 
#unique values in the Index 

# Essential Functionality

Reindexing

In [146]:
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','c','a'])
obj

d    4.5
b    7.2
c   -5.3
a    3.6
dtype: float64

In [151]:

obj.reindex(['a','b','c','d','e'])

a    3.6
b    7.2
c   -5.3
d    4.5
e    NaN
dtype: float64

In [149]:
obj3=pd.Series(['blue','yellow','purple'],index=[0,2,4])
obj3

0      blue
2    yellow
4    purple
dtype: object

In [150]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    yellow
3    yellow
4    purple
5    purple
dtype: object

In [162]:
frame=pd.DataFrame(np.arange(9).reshape(3,3),index=['a','c','d'],columns=["Ohio","Texas","California"])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [163]:
frame2=frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [166]:
states=["Ohio","California","Utah"]
frame.reindex(columns=states)#original frame remains unaffected


Ohio  California  Utah
a     0           2   NaN
c     3           5   NaN
d     6           8   NaN

In [173]:
#frame.loc[['a','b','c','d'],states]
#or
frame.reindex(['a','b','c','d'],columns=states)


Ohio  California  Utah
a   0.0         2.0   NaN
b   NaN         NaN   NaN
c   3.0         5.0   NaN
d   6.0         8.0   NaN

In [174]:
obj3

0      blue
2    yellow
4    purple
dtype: object

In [175]:
obj3.reindex(range(6),fill_value=100)

0      blue
1       100
2    yellow
3       100
4    purple
5       100
dtype: object

In [176]:
obj3.reindex(range(6),method='bfill')

0      blue
1    yellow
2    yellow
3    purple
4    purple
5       NaN
dtype: object

In [177]:
#https://www.geeksforgeeks.org/python-pandas-dataframe-max/

In [178]:
#limit When forward- or backfilling, maximum size gap (in number of elements) to fill.
#tolerance When forward- or backfilling, maximum size gap (in absolute numeric distance) to fill for inexact matches.
#level Match simple Index on level of MultiIndex; otherwise select subset of.
#copy If True, always copy underlying data even if new index is equivalent to old index; if False, do not copy the data when the indexes are equivalent. 

In [182]:
idx=pd.Index([17.2,1.5,26.3,66.4])
idx.copy(dtype='int64')


Int64Index([17, 1, 26, 66], dtype='int64')

In [183]:
#https://www.geeksforgeeks.org/python-pandas-index-copy/

# Dropping entires from an axis

In [184]:
ob=pd.Series(np.arange(6.),index=['A','B','C','D','E','F'])
ob

A    0.0
B    1.0
C    2.0
D    3.0
E    4.0
F    5.0
dtype: float64

In [186]:
new_obj=ob.drop('C')
new_obj

A    0.0
B    1.0
D    3.0
E    4.0
F    5.0
dtype: float64

In [189]:
ob.drop(['A','B'])


C    2.0
D    3.0
E    4.0
F    5.0
dtype: float64

In [190]:
data=pd.DataFrame(np.arange(16).reshape(4,4),index=['Ohio','Colorado','Utah','NewYork'],columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [193]:
data.drop(['Ohio','Colorado'])

one  two  three  four
Utah       8    9     10    11
NewYork   12   13     14    15

In [194]:
data.drop(['one','two'],axis=1)

three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
NewYork      14    15

In [195]:
#or
data.drop('one',axis="columns")

two  three  four
Ohio        1      2     3
Colorado    5      6     7
Utah        9     10    11
NewYork    13     14    15

# Indexing, Selection, and Filtering

In [217]:
obj=pd.Series(np.arange(4.),index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [197]:
obj[1]

1.0

In [200]:
obj['d']

3.0

In [201]:
obj[3]

3.0

In [202]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [203]:
obj[['b','c','d']]

b    1.0
c    2.0
d    3.0
dtype: float64

In [209]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [205]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [207]:
obj['b':'d']

b    1.0
c    2.0
d    3.0
dtype: float64

In [218]:
obj['b':'c']=4.0


In [219]:
obj

a    0.0
b    4.0
c    4.0
d    3.0
dtype: float64

In [221]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])

In [222]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [223]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [227]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [228]:
data[data['three']>5]


one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [229]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [231]:
data[data<7]='F'
data

one two three four
Ohio       F   F     F    F
Colorado   F   F     F    7
Utah       8   9    10   11
New York  12  13    14   15

# Selection with loc iloc

In [2]:
import pandas as pd
data=pd.DataFrame({"Apple":[20,30,40],"Banana":[10,15,12],"Grapes":[20,35,66]},index=['a','b','c'])
data

Apple  Banana  Grapes
a     20      10      20
b     30      15      35
c     40      12      66

In [43]:
data.index.name="Proteins"
data

Apple  Banana  Grapes
Proteins                       
a            20      10      20
b            30      15      35
c            40      12      66

In [7]:
data.loc['a',['Apple','Banana']]

Apple     20
Banana    10
Name: a, dtype: int64

In [10]:
data.loc['b','Apple']

30

In [11]:
data.iloc[2,[0,2]] #index of 'abc' first then 'applebananagrapes'

Apple     40
Grapes    66
Name: c, dtype: int64

In [12]:
data.iloc[2]

Apple     40
Banana    12
Grapes    66
Name: c, dtype: int64

In [21]:
data.iloc[[1,2],[2,1]]

Grapes  Banana
Proteins                
b             35      15
c             66      12

In [38]:
data.iloc[0:3,[2,0,1]]

Grapes  Apple  Banana
Proteins                       
a             20     20      10
b             35     30      15
c             66     40      12

In [19]:
data.loc[:'c','Apple']

Proteins
a    20
b    30
c    40
Name: Apple, dtype: int64

In [26]:
data.iloc[:, :2][data.Banana > 10]

Apple  Banana
Proteins               
b            30      15
c            40      12

# Integer indexes

In [31]:
ser = pd.Series(np.arange(3.))

In [39]:
ser

0    0.0
1    1.0
dtype: float64

In [33]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]

2.0

In [44]:
#df.iloc[:, where]= Selects single column or subset of columns by integer position
#df.iloc[where_i, where_j] =Select both rows and columns by integer position
#df.at[label_i, label_j] =Select a single scalar value by row and column label 
#df.iat[i, j] =Select a single scalar value by row and column position (integers)
#reindex method =Select either rows or columns by labels
#get_value, set_value methods= Select single value by row and column label

In [45]:
ser[:1]

0    0.0
dtype: float64

In [49]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [47]:
ser.iloc[:1]

0    0.0
dtype: float64

# Arthimetic and data alignment

In [51]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
s1


a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [52]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [53]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [56]:

df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1


b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [57]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [58]:
df1+df2  #Since the 'c' and 'e' columns are not found in both DataFrame objects, they appear as all missing in the result. The same holds for the rows whose labels are not common to both objects. 

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [59]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
df1
df2
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

# Arithmetic methods with fill values

In [63]:

df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
df1


a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [61]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [62]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [65]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [66]:
#next example

1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [69]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [70]:
#we can relatedly while reindexing we can specify fill value
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

# Operation between dataframe and series

In [72]:
arr = np.arange(12.).reshape((3, 4))
arr


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [73]:
arr[0]

array([0., 1., 2., 3.])

In [74]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [75]:
#now consider this example

frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [76]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [77]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [80]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [81]:
frame-series2 # when not present in series2 then nan appear

b   d     e   f
Utah    0.0 NaN   1.0 NaN
Ohio    3.0 NaN   4.0 NaN
Texas   6.0 NaN   7.0 NaN
Oregon  9.0 NaN  10.0 NaN

In [83]:
series3=frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [84]:
frame.sub(series3,axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

# Function and mapping

In [87]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame
np.abs(frame)

b         d         e
Utah    0.577087  0.124121  0.302614
Ohio    0.523772  0.000940  1.343810
Texas   0.713544  0.831154  2.370232
Oregon  1.860761  0.860757  0.560145

In [88]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    2.384533
d    0.984879
e    3.714041
dtype: float64

In [90]:
frame.apply(f, axis='columns')

Utah      0.879701
Ohio      1.342870
Texas     1.656688
Oregon    2.420906
dtype: float64

In [91]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -1.860761 -0.860757 -2.370232
max  0.523772  0.124121  1.343810

In [92]:
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    -0.58   0.12   0.30
Ohio     0.52   0.00   1.34
Texas   -0.71  -0.83  -2.37
Oregon  -1.86  -0.86   0.56

In [1]:
##see video of functio and mapping

In [2]:
import pandas as pd
import numpy as np
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame
np.abs(frame)

b         d         e
Utah    0.583319  1.727377  0.135418
Ohio    0.620615  0.399220  1.014811
Texas   0.405170  0.091433  0.635904
Oregon  1.356126  0.344504  1.125117

In [3]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.976741
d    2.126597
e    1.761021
dtype: float64

In [4]:
frame.apply(f, axis='columns')

Utah      1.862796
Ohio      1.635427
Texas     1.041074
Oregon    1.700630
dtype: float64

In [5]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -1.356126 -0.399220 -1.125117
max  0.620615  1.727377  0.635904

In [6]:
format = lambda x: '%.2f' % x
frame.applymap(format)


b      d      e
Utah     0.58   1.73  -0.14
Ohio     0.62  -0.40  -1.01
Texas   -0.41  -0.09   0.64
Oregon  -1.36   0.34  -1.13

In [7]:
frame['e'].map(format)

Utah      -0.14
Ohio      -1.01
Texas      0.64
Oregon    -1.13
Name: e, dtype: object

# Sorting and ranking

# Axis Indexes with Duplicate Labels

In [21]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [22]:
obj.index.is_unique

False

In [23]:
obj['a']

a    0
a    1
dtype: int64

In [24]:
obj['b']

b    2
b    3
dtype: int64

In [29]:
df=pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b'])
df

0         1         2
a  0.065612  0.724069 -0.175005
a  1.290475  0.983858  0.373858
b -0.613405 -2.523899  0.166080
b -1.122300  0.610302  0.849644

In [30]:
df.loc['b']

0         1         2
b -0.613405 -2.523899  0.166080
b -1.122300  0.610302  0.849644

# Summarizing and Computing Descriptive Statistics 

In [38]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [39]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [40]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [43]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [44]:
#Some methods, like idxmin and idxmax, return indirect statistics like the index value where the minimum or maximum values are attained:
df.idxmax()

one    b
two    d
dtype: object

In [45]:
df.idxmax(axis='columns')

a    one
b    one
c    NaN
d    one
dtype: object

In [48]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [51]:
obj=pd.Series(['a','a','b','c']*4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [52]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [53]:
#descriptive and summary stats
#count Number of non-NA values 
#describe Compute set of summary statistics for Series or each DataFrame column 
#min, max Compute minimum and maximum values 
#argmin, argmax Compute index locations (integers) at which minimum or maximum value obtained, respectively 
#idxmin, idxmax Compute index labels at which minimum or maximum value obtained, respectively
#quantile Compute sample quantile ranging from 0 to 1 sum Sum of values 
#mean Mean of values
#median Arithmetic median (50% quantile) of values
#mad Mean absolute deviation from mean value 
#prod Product of all values var Sample variance of values 
#std Sample standard deviation of values skew Sample skewness (third moment) of values
#kurt Sample kurtosis (fourth moment) of values 
#cumsum Cumulative sum of values
#
#cummin, cummax Cumulative minimum or maximum of values, respectively 
#cumprod Cumulative product of values
#diff Compute first arithmetic difference (useful for time series)
#pct_change Compute percent changes

# Correlation and Covariance

In [55]:
import pandas_datareader.data as we

ModuleNotFoundError: No module named 'pandas_datareader'

# Unique Values, Value Counts, and Membership 

In [57]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c']) 
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [58]:
uniques=obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [59]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [61]:
pd.value_counts(obj.values,sort=False)

d    1
a    3
b    2
c    3
dtype: int64

In [62]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [64]:
mask=obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [65]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [66]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [67]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [68]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [69]:
 df = pd.read_csv('C.csv')


In [70]:
df

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [3]:
import pandas as pd
df2=pd.read_csv('example2.csv',header=None)


In [4]:
df2

0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [5]:
df2= pd.read_csv('example2.csv', names=['a', 'b', 'c', 'd', 'message']) 
df2

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo