In [9]:
import numpy as np

In [14]:
 arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [2]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.empty((6,6))# returns anything in memory

array([[ 1.36357933e-312,  1.36358190e-312,  1.36806943e-313,
         1.17446525e-308,  1.33360293e+241,  4.51556701e+257],
       [ 4.78104776e+180,  7.68283953e+170,  3.53860623e-308,
         1.33360316e+241,  4.58733050e-310,  3.42196483e-210],
       [ 6.46048250e-313,  7.35534669e-308,  1.33360317e+241,
         4.96759215e-310,  1.37186216e+142,  2.02534551e-312],
       [ 4.32672565e-307,  1.33360336e+241,  8.87885479e-310,
         2.14800214e-152,  3.91408755e-313,  2.56513642e-308],
       [-3.38460681e+125,  3.69028917e+180,  1.58254032e-307,
         1.09403822e-303,  1.27612992e-303,  1.27612715e-303],
       [ 4.31280139e-188,  1.86197390e-178,  3.42251026e-159,
         8.83311043e+067,  5.97766297e-310,  7.84455929e-307]])

In [4]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
l=[1,2,3,4,5]
np.array(l) # list converted into narray

array([1, 2, 3, 4, 5])

In [7]:
x=np.arange(1,100,10)

In [8]:
x.shape

(10,)

In [14]:
x=np.zeros((10,10))

In [15]:
x.shape

(10, 10)

In [17]:
y=x.reshape((2,2,5,5)) #to reshape the num of elements should be same as before which was 100 so 2*2*5*5 is also 100

In [18]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [19]:
y.dtype

dtype('float64')

In [21]:
y.ndim #dimention of array

4

Arthimetic with ndarray

Vectorization
-Express batch operation on data without writing loops
-Any arthimetic operation between equal size array applies operation element wise
-Arthimetic operation with scalar propagate the scalar argument to each element in the array

In [22]:
arr=np.array([[1,2,3] ,[4,5,6]]) # should be same size for vectorization

In [23]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [24]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [25]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [26]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [31]:
#comparison
arr2=np.array([[11,0,33],[7,8,9]])
arr2

array([[11,  0, 33],
       [ 7,  8,  9]])

In [32]:
arr>arr2

array([[False,  True, False],
       [False, False, False]])

In [33]:
a=np.random.randn((10))

In [34]:
b=np.random.randn((10))

In [35]:
a

array([-0.03543383, -0.10049506,  0.53648951, -1.42406404, -0.54101908,
       -1.16908014,  0.38922147,  0.01871049, -0.2303157 ,  1.46390435])

In [36]:
b

array([-0.93084709,  1.10496678,  0.0362825 , -0.09843017,  0.17999563,
       -0.7083447 , -1.3016808 , -1.08764749,  1.48768475, -1.20499108])

In [37]:
a+b

array([-0.96628092,  1.00447172,  0.57277201, -1.52249421, -0.36102345,
       -1.87742484, -0.91245932, -1.068937  ,  1.25736905,  0.25891327])

In [38]:
2*a

array([-0.07086766, -0.20099012,  1.07297902, -2.84812808, -1.08203815,
       -2.33816027,  0.77844295,  0.03742097, -0.4606314 ,  2.9278087 ])

In [39]:
a>0

array([False, False,  True, False, False, False,  True,  True, False,
        True])

In [40]:
a[a>0]

array([0.53648951, 0.38922147, 0.01871049, 1.46390435])

Indexing and slicing

In [41]:
import numpy as np


In [43]:
x=np.array([1,7,9,8,5])

In [45]:
x[4]

5

In [46]:
x[x>5] #boolean indexing

array([7, 9, 8])

In [48]:
x[[2,1]] #fancy indexing (give index number to access it)

array([9, 7])

In [51]:
x=np.random.randn(10,10)

In [52]:
x

array([[ 0.70759651,  0.50065427, -0.02314008,  0.38738194, -0.28259968,
         0.50969767, -0.97042364,  0.70637436, -1.16292759, -0.21686356],
       [ 1.21412764, -0.68317952,  0.11336668,  0.81609824, -0.57013396,
         0.12489881, -0.83617706, -1.3885793 ,  0.09405429,  0.99842301],
       [ 0.35912834, -0.09232834, -1.35976674, -0.05232404, -0.02008844,
         0.71152732, -0.22949232, -1.77303641,  0.49360983, -0.40720284],
       [ 1.14022992, -0.96127224, -1.71399856, -0.28341435, -0.41841868,
        -0.57714775, -0.46669642, -1.24590814,  0.99517983,  1.11492462],
       [ 1.26977503,  0.97328639,  1.52909982, -1.42224498, -0.44508931,
         0.07796263, -0.56074039, -0.07778442, -0.3792672 , -0.72746724],
       [ 1.18950804,  1.38414975, -1.52723983,  0.53959646, -1.25349711,
        -0.79496792,  2.38027265, -0.49988717, -0.27873678, -0.81091869],
       [ 0.94455813, -0.95058138,  0.30320206, -1.46805314,  0.58064099,
         0.11068538,  0.96159238,  0.66982573

In [53]:
x[0] #gets first row

array([ 0.70759651,  0.50065427, -0.02314008,  0.38738194, -0.28259968,
        0.50969767, -0.97042364,  0.70637436, -1.16292759, -0.21686356])

In [54]:
x[0][4]

-0.28259968428075644

In [56]:
x[1:10:2] #odd rows 

array([[ 1.21412764, -0.68317952,  0.11336668,  0.81609824, -0.57013396,
         0.12489881, -0.83617706, -1.3885793 ,  0.09405429,  0.99842301],
       [ 1.14022992, -0.96127224, -1.71399856, -0.28341435, -0.41841868,
        -0.57714775, -0.46669642, -1.24590814,  0.99517983,  1.11492462],
       [ 1.18950804,  1.38414975, -1.52723983,  0.53959646, -1.25349711,
        -0.79496792,  2.38027265, -0.49988717, -0.27873678, -0.81091869],
       [-0.69872477, -0.41422142, -0.88523122, -1.03709726,  0.89613782,
        -0.1351368 ,  0.37168949, -1.12135347, -1.38767032,  2.0177236 ],
       [ 0.72779264,  0.08287792, -0.16370574, -0.08311496,  0.53027712,
        -0.32214514,  1.51982179, -0.43620614,  0.1676908 ,  1.36851158]])

In [57]:
x[::,0:4]   # [allrows,0to4 columns]

array([[ 0.70759651,  0.50065427, -0.02314008,  0.38738194],
       [ 1.21412764, -0.68317952,  0.11336668,  0.81609824],
       [ 0.35912834, -0.09232834, -1.35976674, -0.05232404],
       [ 1.14022992, -0.96127224, -1.71399856, -0.28341435],
       [ 1.26977503,  0.97328639,  1.52909982, -1.42224498],
       [ 1.18950804,  1.38414975, -1.52723983,  0.53959646],
       [ 0.94455813, -0.95058138,  0.30320206, -1.46805314],
       [-0.69872477, -0.41422142, -0.88523122, -1.03709726],
       [-0.70506926, -1.43591877, -0.29662281,  0.00536973],
       [ 0.72779264,  0.08287792, -0.16370574, -0.08311496]])

In [64]:
x=np.ones((5,5))

In [67]:
x[0:-1,1:-1]=0

In [68]:
x

array([[1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Fast element wise array functions

In [69]:
x=np.array([1,2,3,4,5])

In [70]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [72]:
np.power(x,2) #square

array([ 1,  4,  9, 16, 25], dtype=int32)

In [73]:
y=[7,1,2,3,6]

In [75]:
np.maximum(x,y)

array([7, 2, 3, 4, 6])

In [3]:
import numpy as np
#npwhere (ternaryoperator)
salary=np.array([0,-1,1,2,100,1000])
np.where(salary<10,250,salary)

array([ 250,  250,  250,  250,  100, 1000])

Statistical


In [4]:
import numpy as np
x=np.array([10,9,7,10,7])

In [6]:
x.mean()

8.6

In [11]:
x.cumsum() #cummulative sum
#second eleement sum of 1st and 2nd  third element sum of 1st 2nd 3rd and so on....

array([10, 19, 26, 36, 43], dtype=int32)

In [12]:
x.cumprod() #cummulative product

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [13]:
#boolean function (works on bool values) all sum any
y=x>5

In [14]:
y

array([ True,  True,  True,  True,  True])

In [15]:
y.sum() #returns number of true values

5

In [16]:
y.any() #returns true if found any true

True

In [17]:
y.all() #returns true if found all true

True

In [18]:
x

array([10,  9,  7, 10,  7])

In [19]:
x.sort()  #sorts the array

In [20]:
x

array([ 7,  7,  9, 10, 10])

In [22]:
np.unique(x) #finds unique elements

array([ 7,  9, 10])


FILE INPUT OUTPUT 
-np.save(filename.npy,array) 
-np.load(filename.npy)
-np.savez(filename.npz,array1,array2)
-When loading an .npz file you get  back the dict-like object

In [85]:
import numpy as np


In [86]:
n=[1,4,5,7]


In [87]:
y=[8,7,9]


In [88]:
np.save("testx",n) #can provide npy extenstion if u want

In [89]:
loadx=np.load("testx.npy")

In [90]:
loadx

array([1, 4, 5, 7])

In [95]:
np.savez("testxy",n=n,y=y)

In [96]:
loadxy=np.load("testxy.npz")

In [97]:
loadxy

In [98]:
loadxy['n']

array([1, 4, 5, 7])

Linear algebra

In [108]:
#see more linear functions
import numpy as np
x=np.random.randn(3,2)

In [111]:
y=np.random.randn(2,3)

In [118]:
x.dot(y)

array([[-0.30632944, -1.09162166,  0.76565108],
       [ 1.24288822, -1.89226013,  0.42675099],
       [ 0.77104637, -0.94777517,  0.13835426]])

In [113]:
x.transpose()

array([[ 0.01567158, -0.83067185, -0.48788181],
       [-1.29257089, -1.75392621, -0.83774101]])

In [114]:
x.trace()

-1.7382546347482684

Pseudu Random number

In [119]:
#to remove baisness random is used bc same can be in sequence data
#normal()
#seed()
#gamma()
#uniform()

In [120]:
import numpy as np

In [121]:
np.random.seed(7) #seed value is first used to initailize random number

In [122]:
np.random.normal(size=(3,3)) #makes 3 by 3 using noraml distrubution

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [123]:
np.random.uniform(size=(3,4)) #uniform distribution

array([[0.38094113, 0.06593635, 0.2881456 , 0.90959353],
       [0.21338535, 0.45212396, 0.93120602, 0.02489923],
       [0.60054892, 0.9501295 , 0.23030288, 0.54848992]])

Numpy advance array manipulation

In [124]:
#reshaping# 
#c order= rowmajor
#fortran order( column major) or "order f"
#arr.reshape((4,3),order=?)

In [137]:

a=np.arange(5)

In [138]:
a.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [139]:
a.repeat([2,3,2,5,8])

array([0, 0, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4])